#!/usr/bin/env bash

######################################
# LUADNS DDNS UPDATE SCRIPT
######################################
# Github Page: https://github.com/zoot101/luadns-ddns
######################################

# Script Version
version="2.0.0"

# Modern error handling
set -euo pipefail

######################################
# Script Variables
######################################
# Luadns API URL
readonly luadns_api_url="https://api.luadns.com/v1"

# Luadns Standard Nameservers
readonly -a luadns_nameservers=( 
  "ns1.luadns.net"
  "ns2.luadns.net"
  "ns3.luadns.net"
  "ns4.luadns.net"
)

# File to Store Last IP Check & Update Status
readonly working_dir="/var/lib/luadns-ddns"
readonly last_ip_check_file="${working_dir}/last-ip-check.txt"
readonly last_update_status_file="${working_dir}/last-update-status.txt"

# Wait between API calls
readonly wait_time=3

# Number of retries for curl
readonly curl_retries=3

######################################
# Main Function
######################################
main() {

  # Check Dependencies
  check_dependencies

  # Unset all Variables
  unset_all_vars

  # Parse Input Arguments
  parse_arguments "$@"

  # Read Config File
  read_and_check_config_file

  # Create Logfiles
  generate_logfiles

  # Print Greeting
  print_greeting

  # Print User, Zone and Zone Records & Exit if -i, --info is used
  if [[ "${print_info_arg}" == "yes" ]]; then
    print_luadns_info
    clean_up_logfiles
    exit 0
  fi

  # Check for Forced Update
  check_for_forced_update

  # Get Public IP
  get_public_ip

  # Check for IP Change [if not forced]
  if [[ "${force_update}" == "no" ]]; then
    check_for_ip_change "${public_ip}"
  fi
  log_to_email ""

  # If the IP Changes, or if the Update is Forced - Update the Record(s)
  # Verify them and Record the Public IP & Update Status
  if [[ "${force_update}" == "yes" || "${ip_change}" == "yes" ]]; then
    update_dns_records
    verify_dns_records
    notify_and_record_success
  fi

  # Clean Up Logfiles & Exit
  clean_up_logfiles
  exit 0
}

######################################
# Script Functions
######################################
# Logging Functions
log() {
  printf '%s\n' "$*"
}
log_to_email() {
  printf '%s\n' "$*" | tee -a "${logfile}"
}
log_to_hook() {
  printf '%s\n' "$*" | tee -a "${hook_logfile}" &>"/dev/null"
}
log_to_both() {
  printf '%s\n' "$*" | tee -a "${logfile}" "${hook_logfile}"
}

# Error Function
error() {
  printf '%s\n' "ERROR: $*"
  exit 1
}

# Dig Command if the query_source_ip parameter is defined
dig_cmd() {
  if [[ -n "${outgoing_interface_ip}" ]]; then
    dig -b "${outgoing_interface_ip}" +short +retry=3 "$@"
  else
    dig +short +retry=3 "$@"
  fi
}

# Query Auth Nameserver for TXT Record Deployed using dig
query_nameserver() {
  local auth_server="${1}"
  local name="${2}"
  local content="${3}"
  dig_cmd @"${auth_server}" A "${name}" | tr -d '"' | grep -Fxq "${content}"
}

# Curl Command For API Calls (Use Non-Default Interface if Specified)
curl_api_call() {
  if [[ -z "${outgoing_interface_ip}" ]]; then
    curl --silent --show-error --retry "$curl_retries" -u "${luadns_email}:${luadns_api_key}" \
                                                     -H 'Accept: application/json' "$@"
  else
    curl --interface "${outgoing_interface_ip}" --silent --show-error --retry "$curl_retries" \
                      -u "${luadns_email}:${luadns_api_key}" -H 'Accept: application/json' "$@"
  fi
}

# Function to check if a Variable is a number >= 0
is_number() {
  local number_regex='^[0-9]+$'
  if ! [[ "$1" =~ $number_regex ]]; then
    return 1
  else
    return 0
  fi
}

# Unset all Vars
unset_all_vars() {

  # Input Args
  using_custom_config=
  force_update_arg=
  force_update=
  print_info_arg=

  # Config File Variables
  config_file0=
  script_directory=
  config_file1=
  config_file2=
  public_ip_source=
  public_ip_interface=
  public_ip_http_servers=()
  public_ip_dns_commands=()
  times_to_update=()
  luadns_email=
  luadns_api_key=
  dns_zone_name=
  dns_record_names=()
  outgoing_interface_ip=
  email_address=
  muttrc_path=
  notification_hook=

  # Other
  disable_emails="yes"
  system_hostname=
  os_name=
  public_ip=
  last_ip=
  ip_change=
  last_update_failed="no"
}

# Parse Input Arguments
parse_arguments() {

  # Valid arguments: -c, -h, -i, -f
  while (( ${#} )); do
    case "${1}" in
      # Custom Config Argument
      -c|--config)
        shift 1
        if (( $# == 0 )); then
          error "Specified custom config file, but none given - Exiting"
        fi
        if [[ ! -r "${1}" ]]; then
          error "Custom Config File given:" "${1}" "does not exist or is not readable - Exiting"
        else
          using_custom_config="yes"
          config_file0="${1}"
        fi
      ;;

      # Force Update Argument
      -f|--force)
        force_update_arg="yes"
      ;;

      # Print Information Argument
      -i|--info)
        print_info_arg="yes"
      ;;

      # Help Message
      -h|--help)
        print_help
      ;;

      # Unsupported Arguments
      *)
        log "ERROR: Unsupported argument:" "${1}"
        print_help
      ;;
    esac
    shift 1
  done

  # Check For Undefined Args
  if [[ -z "${using_custom_config}" ]]; then using_custom_config="no"; fi
  if [[ -z "${force_update_arg}" ]]; then force_update_arg="no"; fi
  if [[ -z "${print_info_arg}" ]]; then print_info_arg="no"; fi
}

# Print a Quick Help Message and Exit
print_help() {
  log ""
  log "Usage: luadns-ddns            [OPTIONS...]"
  log ""
  log "  -f, --force                 Force an update of the record regardless of time or"
  log "                              whether an IP Change is detected"
  log "  -c, --config                Override the default config file. Could be useful to"
  log "                              update multiple records"
  log "  -i, --info                  Querys the Luadns REST API Endpoints for the user details,"
  log "                              zones, zone records and exits. Allows testing the login"
  log "                              credentials and inspecting the Zone/Records."
  log "  -h, --help                  Print help"
  log ""
  log "Manual Entries:"
  log "  Main Script:                luadns-ddns(1)      $ man luadns-ddns"
  log ""
  exit 0
}

# Check Essential Dependencies are Installed
check_dependencies() {
  local dependencies=( "curl" "jq" "mktemp" "grep" "date" "dig" "mktemp" "tee" "sleep")
  for cmd in "${dependencies[@]}"; do
    if ! command -v "${cmd}" &>/dev/null; then
      error "${cmd} is not installed/found in \$PATH - Exiting"
    fi
  done
}

# Read and Check the Config File
read_and_check_config_file() {

  # Determine Script Directory & Define Config File 1 & 2
  script_directory="$(dirname "$(readlink -f "${0}")")"
  config_file1="/etc/luadns-ddns.conf"
  config_file2="${script_directory}""/luadns-ddns.conf"

  # Pick Config File in Order of Preference
  if [[ "${using_custom_config}" == "yes" ]]; then
    log "INFO: Config File: ${config_file0}"
    # shellcheck source=./config/luadns-ddns.conf
    source "${config_file0}"
  elif [[ -r "${config_file1}" ]]; then
    log "INFO: Config File: ${config_file1}"
    # shellcheck source=./config/luadns-ddns.conf
    source "${config_file1}"
  elif [[ -r "${config_file2}" ]]; then
    log "INFO: Config File: ${config_file2}"
    # shellcheck source=./config/luadns-ddns.conf
    source "${config_file2}"
  else
    error "Config File not found in the following locations - 1: ${config_file1}, 2: ${config_file2} - Exiting"
  fi

  # Check if the Public IP Source is defined correctly
  if [[ -z "${public_ip_source}" ]]; then
    error "No public_ip_source defined in Config File - Exiting"
  elif [[ "${public_ip_source}" != "Local Interface" && \
          "${public_ip_source}" != "HTTP Server" && \
          "${public_ip_source}" != "DNS Query" ]]; then
    error "Invalid value for Parameter public_ip_source: ${public_ip_source} in Config File - Exiting"
  fi

  # Check if the required information is defined based on what
  # source is being used for the Public IP

  # 1. Check interface is defined and that it is a valid interface
  if [[ "${public_ip_source}" == "Local Interface" ]]; then
    if [[ -z "${public_ip_interface}" ]]; then
      error "Using public_ip_interface=\"Local Interface\", but no interface (public_ip_interface) given in Config File - Exiting"
    fi
    if ! ip a | grep -qw "${public_ip_interface}"; then
      error "Using public_ip_interface=\"Local Interface\", but interface name: ${public_ip_interface} not found - Exiting"
    fi
  fi

  # 2. Check at least one HTTP Server is defined if using the HTTP Method
  if [[ "${public_ip_source}" == "HTTP Server" ]]; then
    if (( ${#public_ip_http_servers[@]} == 0 )); then
      error "Using public_ip_source=\"HTTP Server\", but no HTTP Servers (public_ip_http_servers) defined in Config File - Exiting"
    fi
  fi

  # 3. Check at least one Command is defined if using the DNS Query Method
  if [[ "${public_ip_source}" == "DNS Query" ]]; then
    if (( ${#public_ip_dns_commands[@]} == 0 )); then
      error "Using public_ip_source=\"DNS Query\", but no DNS Commands (public_ip_dns_commands) defined in Config File - Exiting" 
    fi
  fi

  # Now Check the Times to Update are Specified and as valid times (HH:MM)
  if (( ${#times_to_update[@]} == 0 )); then
    error "No times_to_update specified in Config File - Exiting"
  fi
  for time in "${times_to_update[@]}"; do
    if [[ ! $time =~ ^([01][0-9]|2[0-3]):[0-5][0-9]$ ]]; then
      error "Invalid time: '$time' (expected HH:MM) specifed in times_to_update in Config File - Exiting"
    fi
  done

  # Check LuaDNS Credentials are defined
  if [[ -z "${luadns_email}" ]]; then
    error "No Luadns Email Login (luadns_email) parameter defined in Config File - Exiting"
  fi
  if [[ -z "${luadns_api_key}" ]]; then
    error "No Luadns API Key (luadns_api_key) parameter defined in Config File - Exiting"
  fi

  # Check The Zone Name is Defined and that at least 1 Record is defined
  if [[ -z "${dns_zone_name}" ]]; then
    error "No DNS Zone Name (dns_zone_name) parameter defined in Config File - Exiting"
  fi
  if (( ${#dns_record_names[@]} == 0 )); then
    error "No DNS Records (dns_record_names) defined in Config File - Exiting"
  fi

  # Now Check Each of the Records are Part of the Given DNS Zone - Exit if not
  for record in "${dns_record_names[@]}"; do
    if [[ "${record}" != "${dns_zone_name}" && "${record}" != *."${dns_zone_name}" ]]; then
      error "DNS Record: ${record} is not in DNS zone ${dns_zone_name}"
    fi
  done

  # Check if one specified an outgoing interface IP
  if [[ -n "${outgoing_interface_ip}" ]]; then
    if ! ip a | grep -qw "${outgoing_interface_ip}"; then
      error "Using outgoing_interface_ip=${outgoing_interface_ip} in Config File, but IP not found on local network interfaces - Exiting"
    fi
  fi

  # Now Decide if Emails are Going to be Sent or Not
  if [[ -z "${email_address}" ]]; then
    log "INFO: No Email Address (email_address) defined in Config File - Emails Disabled"
    disable_emails="yes"
  elif [[ -z "${muttrc_path}" ]]; then
    log "INFO: No MuttRC File (muttrc_path) not defined in Config File - Emails Disabled"
    disable_emails="yes"
  elif [[ ! -r "${muttrc_path}" ]]; then
    log "INFO: MuttRC File (muttrc_path) defined in Config File does not exist or is not readable - Emails Disabled"
    disable_emails="yes"
  else
    disable_emails="no"
  fi

  # Check if mutt is installed - If not disable emails
  if ! command -v mutt &> /dev/null; then
    log "INFO: mutt is not installed/found in PATH - Emails Disabled"
    disable_emails="yes"
  fi

  # Lastly, check the notification hook is executable if defined
  if [[ -n "${notification_hook}" ]]; then
    if [[ ! -x "${notification_hook}" ]]; then
      error "Notification Hook: ${notification_hook} in Config File not found or not executable - Exiting"
    fi
  fi

  # Check if the working directory is writable
  if [[ ! -w "${working_dir}" ]]; then
    error "Working Directory: ${working_dir} is not writable - Exiting"
  fi 

  # Print out Config File is OK
  log "INFO: Config File: OK"
  log ""
}

# Generate Logfiles
generate_logfiles() {
  logfile=$(mktemp -t "luadns-ddns.email.XXXXX.txt")
  hook_logfile=$(mktemp -t "luadns-ddns.XXXXX.txt")
}

# Print Greeting
print_greeting() {
  # Get the Hostname & OS Name if possible
  if command -v hostname &>/dev/null; then
    system_hostname=$(hostname --fqdn) &> "/dev/null"
  else
    system_hostname="Unknown"
  fi
  if [[ -f "/etc/os-release" ]]; then
    os_name=$(awk -F \" '/^PRETTY_NAME=/ {print $2}' "/etc/os-release")
  else
    os_name="Unknown"
  fi

  # Start the Hook Body slightly different
  log_to_hook "Luadns-DDNS on ${system_hostname}"
  log_to_hook " * Version: ${version}"

  # Main Greeting
  log_to_email "##############################"
  log_to_email "# Luadns.com DDNS Version:" "${version}"
  log_to_email "##############################"
  log_to_email "Initialized at $(date +%H:%M:%S) on $(date +%d/%m/%Y)"
  log_to_email " * Luadns.com API URL:" "${luadns_api_url}"
  if [[ -n "${system_hostname}" ]]; then log_to_email " * Hostname: ${system_hostname}"; fi
  if [[ -n "${os_name}" ]]; then log_to_both " * Host OS: ${os_name}"; fi
  log_to_email "Input Options:"
  if [[ "${public_ip_source}" == "Local Interface" ]]; then
    log_to_email " * Public IP Source: Local Interface: ${public_ip_interface}"
  elif [[ "${public_ip_source}" == "HTTP Server" ]]; then
    log_to_email " * Public IP Source: HTTP Server(s)"
  elif [[ "${public_ip_source}" == "DNS Query" ]]; then
    log_to_email " * Public IP Source: DNS Query"
  fi
  log_to_email " * DNS Zone Name: ${dns_zone_name}"
  log_to_both " * DNS Records to Update:"
  for record in "${dns_record_names[@]}"; do
    log_to_both "   - ${record}"
  done
  if [[ -n "${outgoing_interface_ip}" ]]; then
    log_to_email " * Outgoing Interface IP: ${outgoing_interface_ip}"
  fi
  if [[ "${disable_emails}" == "no" ]]; then
    log_to_email " * Email Notifications: YES"
  else
    log_to_email " * Email Notifications: NO"
  fi
  if [[ -n "${notification_hook}" ]]; then
    log_to_email " * Notification Hook: YES"
  else
    log_to_email " * Notification Hook: NO"
  fi
  log_to_email "Runlog is below:"
  log_to_email ""
}

# Check for Forced Update: -f arg, time or previous status check
check_for_forced_update() {
  log_to_email "Update the DNS Record(s) Regardless?"

  # If the Force Update Arg was given earlier
  # 1. If the -f or --force input argument was given
  # 2. If the script has not been ran before: the Last IP or Status Check Files don't exist
  # 3. If the status of the previous update returned an error upon querying the DNS Servers
  #    for the records
  # 4. Otherwise cycle through the times to see if theres a match
  if [[ "${force_update_arg}" == "yes" ]]; then
    force_update="yes"
    log_to_email " * Yes [Forced]"
  elif [[ ! -f "${last_ip_check_file}" || ! -f "${last_update_status_file}" ]]; then
    force_update="yes"
    log_to_email " * Yes [1st Run of Script]"
  elif [[ "$(cat "${last_update_status_file}")" != "ok" ]]; then
    last_update_failed="yes"
    force_update="yes"
    log_to_email " * Yes [Last Update Failed?]"
  else
    n_times=${#times_to_update[@]}
    current_time=$(date +"%H:%M")
    for ((i=0; i<=(n_times-1); i++)); do
      if [[ "${current_time}" == "${times_to_update[$i]}" ]]; then
        force_update="yes"
        log_to_email " * Yes [Time: ${current_time}]"
        break
      elif [[ $i == $((n_times-1)) ]]; then
        log_to_email " * No"
        force_update="no"
      fi
    done
  fi
  log_to_email ""
}

# Validate an IPv4 Address
is_valid_ipv4() {
  local ip=$1
  local octet='(25[0-5]|2[0-4][0-9]|1[0-9]{2}|[1-9]?[0-9])'
  [[ $ip =~ ^${octet}\.${octet}\.${octet}\.${octet}$ ]]
}


# Get the Public IP using each of the 3 methods
get_public_ip() {
  log_to_email "Checking Public IP..."

  # Method 1: Local Interface
  if [[ "${public_ip_source}" == "Local Interface" ]]; then
    log_to_email " * Checking IP on Interface: ${public_ip_interface}"
    public_ip="$(ip -4 addr show "${public_ip_interface}" | awk '/inet/ { sub(/\/.*/,""); print $2; exit}')"
    if ! is_valid_ipv4 "${public_ip}"; then
      log_to_both " * Invalid IP Obtained from ${public_ip_interface} - Exiting"
      notify_and_record_warning
      exit 1
    else
      log_to_email " * Got Public IP: ${public_ip}"
    fi

  # Method 2: HTTP Server(s)
  elif [[ "${public_ip_source}" == "HTTP Server" ]]; then
    log_to_email " * Checking Public IP using defined HTTP Servers..."
    N_servers=${#public_ip_http_servers[@]}
    if [[ -n "${outgoing_interface_ip}" ]]; then
      curl_args=( --interface "${outgoing_interface_ip}" --silent --retry "$curl_retries" )
    else
      curl_args=( --silent --retry "$curl_retries" )
    fi
    for ((i=0; i<=(N_servers-1); i++)); do
      log_to_email " * Trying Server $((i+1))/$N_servers: ${public_ip_http_servers[$i]}..."
      if public_ip="$( curl "${curl_args[@]}" "${public_ip_http_servers[$i]}" )"; then
        if ! is_valid_ipv4 "${public_ip}"; then
          log_to_email " * Public IP obtained from ${public_ip_http_servers[$i]} not valid - Trying Next Server..."
        else
          log_to_email " * Got Public IP: ${public_ip}"
          break
        fi
      else
        if (( i == (N_servers-1) )); then
          log_to_email " * Could not get a Public IP from ${public_ip_http_servers[$i]} either"
          log_to_both " * All HTTP Servers tried - Exiting"
          notify_and_record_warning
          exit 1
        else
          log_to_email " * Could not get a Public IP from ${public_ip_http_servers[$i]} - Trying Next Server..."
        fi
      fi
    done 

  # Method 3: DNS Query
  elif [[ "${public_ip_source}" == "DNS Query" ]]; then
    log_to_email " * Checking Public IP with DNS using defined commands..."
    N_commands=${#public_ip_dns_commands[@]}
    for ((i=0; i<=(N_commands-1); i++)); do
      log_to_email " * Trying Command $((i+1))/$N_commands : ${public_ip_dns_commands[$i]}"
      if public_ip="$(eval "${public_ip_dns_commands[$i]} 2>/dev/null" )"; then
        if ! is_valid_ipv4 "${public_ip}"; then
          log_to_email " * Invalid IP Recevied - Trying Next Command..."
        else
          log_to_email " * Got Public IP: ${public_ip}"
          break
        fi
      else
        if (( i == (N_commands-1) )); then
          log_to_both " * All DNS Commands Unsuccessful - Exiting"
          notify_and_record_warning
          exit 1
        else
          log_to_email " * Command Unsuccessful - Trying next one..."
        fi
      fi 
    done
  fi
} 

# Check for IP Change
check_for_ip_change() {
  local ip="${1}"
  local last_ip
  last_ip="$(cat "${last_ip_check_file}")"
  if [[ "${ip}" != "${last_ip}" ]]; then
    log_to_both " * IP Change Detected!"
    log_to_both "    - Last IP: ${last_ip}"
    log_to_both "    - New IP: ${public_ip}"
    log_to_email " * Proceeding to Update Record(s)..."
    ip_change="yes"
  else
    log_to_email " * IP Change NOT Detected!"
    ip_change="no"
  fi
}

######################################
# LuaDNS.com Related Functions 
######################################
# Official Documentation is https://www.luadns.com/api.html

# Check the Zone is hosted at Luadns.com
check_zone_is_valid() {
  local zone="${1}"

  # Get Number of Nameservers
  N_luadns_nameservers=${#luadns_nameservers[@]}
  # Step Through Each of the Luadns Nameservers
  for ((i=0; i<=(N_luadns_nameservers-1); i++)); do
    if dig @"${luadns_nameservers[$i]}" +short NS "${zone}" &> /dev/null; then
      log_to_email " * Got Valid NS records for" "${zone}" "from" "${luadns_nameservers[$i]}"
      break
    elif [[ $i == $((N_luadns_nameservers-1)) ]]; then
      log_to_both "No NS records found at Luadns for" "${zone}" "- Exiting"
      notify_and_record_warning
      exit 1
    else
      log_to_email " * Could Not Obtain NS records for" "${zone}" "from" "${luadns_nameservers[$i]}" "- Trying Next Server"
      sleep 1
    fi
  done
}

# Validate that valid json data was received from the LuaDNS API
check_response_was_valid() {
  if ! jq -e . >/dev/null <<<"$1"; then
    log_to_both " * Invalid JSON returned from LuaDNS API - Exiting"
    notify_and_record_warning
    exit 1
  fi
}

# Get the Zone ID
luadns_get_zone_id() {
  local response
  local luadns_zone_name="${1}"
  if ! response="$(curl_api_call "${luadns_api_url}"/zones)"; then response="invalid";fi
  check_response_was_valid "${response}"

  # Parse Response with jq command to pick out the Zone ID & Check if it's a number
  if ! zone_id="$(jq -r --arg zone "$luadns_zone_name" '.[] | select(.name==$zone).id' <<<"${response}")"; then zone_id="invalid"; fi
  if ! is_number "${zone_id}"; then
    log_to_both " * Zone ID could not be obtained - Problem with API Key?"
    notify_and_record_warning
    exit 1
  else
    log_to_email " * Got Valid Zone ID for ${luadns_zone_name} from LuaDNS API"
  fi

  # Add some wait time to space out API Calls
  sleep $wait_time
}

# Get the Record ID for a given record using the Luadns.com API
luadns_get_record_id() {
  local luadns_zone_id="${1}"
  local luadns_record_name="${2}"
  local response

  # Add trailing dot if not present - required for the Record ID
  if [[ "${luadns_record_name:0-1}" != "." ]]; then luadns_record_name+="."; fi

  # Get the record id for the above record using the API & Check Response
  if ! response="$(curl_api_call "${luadns_api_url}/zones/${luadns_zone_id}/records")"; then response="invalid"; fi
  check_response_was_valid "${response}" 

  # Process the json data received to select A Type & Name & Check Response
  if ! record_id="$(jq -r --arg record_name "${luadns_record_name}" \
                          --arg record_type "A" \
                    '.[] | select(.name==$record_name and .type==$record_type).id' <<<"${response}")"; then
    log_to_both " * Error getting Record ID from received json - Does the record exist?"
    notify_and_record_warning
    exit 1
  fi
  if is_number "${record_id}"; then
    log_to_email "    - Got Valid Record ID"
  fi

  # Add some wait time to space out API Calls
  sleep $wait_time
}

# Update the DNS Record
luadns_update_record() {
  local zone_id="${1}" 
  local record_name="${2}"
  local record_content="${3}"
  local record_id="${4}" 
  local response success_check json_payload

  # Check for Trailing dot, if it's not there add it - Required for Record ID
  if [[ "${record_name:0-1}" != "." ]]; then record_name="${record_name}""."; fi

  # Update Record as per official API Documentation & Check Response
  # Note that --argjson is needed when "id": 12 is expected instead of "id": "12"
  json_payload="$( jq -n --argjson zone_id "$zone_id" --arg name "$record_name" \
                         --argjson record_id "$record_id" --arg content "$record_content" \
    '{
       zone_id: $zone_id,
       id: $record_id,
       name: $name,
       type: "A",
       content: $content
     }'
  )"

  # Do the Record Update using the API Documentation & Check Response is Valid
  if ! response="$( curl_api_call -X PUT --data "${json_payload}" "${luadns_api_url}/zones/${zone_id}/records/${record_id}")"; then response=null; fi
  check_response_was_valid "${response}"

  # Check for the same public IP given in the response 
  if ! success_check=$(jq -r ".content" <<<"${response}"); then success_check=null; fi
  if [[ "${success_check}" == "${record_content}" ]]; then
    log_to_email "    - Record updated to ${record_content}"
  else

    # NOTE: Might be better to retry the update here...
    log_to_both " * Problem Updating Record - Exiting"
    notify_and_record_warning
    exit 1
  fi

  # Add some wait time to space out API Calls
  sleep $wait_time
}

# Update the Record(s)
update_dns_records() {

  log_to_email "Updating DNS Record(s)..."

  # Step 1: Check Zone is Hosted at Luadns.com. Query NS Records
  check_zone_is_valid "${dns_zone_name}"

  # Step 2: Get the Zone ID
  luadns_get_zone_id "${dns_zone_name}"

  # Step 3: Update Each of the Records: Get the Record ID & Then do the update
  local N_records=${#dns_record_names[@]}
  for ((i=0; i<=(N_records-1); i++)); do
    log_to_email " * Updating Record $((i+1))/$N_records: ${dns_record_names[$i]}..."
    luadns_get_record_id "${zone_id}" "${dns_record_names[$i]}"
    luadns_update_record "${zone_id}" "${dns_record_names[$i]}" "${public_ip}" "${record_id}"
  done
  log_to_email ""
}

# Print Luadns.com Information and Exit
print_luadns_info() {

  log "Querying Luadns.com REST API Information Endpoints"

  # Step 1: Check Zone is Hosted at Luadns.com. Query NS Records
  check_zone_is_valid "${dns_zone_name}"

  # Step 2: Get the Zone ID
  luadns_get_zone_id "${dns_zone_name}"

  # Query Each of the Endpoints [No Error Checking is done here]
  # 1. User Information
  log " * Querying User Information Endpoint..."
  log " * ${luadns_api_url}/users/me"
  log " * Json Response is shown below:"
  curl_api_call "${luadns_api_url}/users/me" | jq || true
  sleep $wait_time
  log ""

  # 2. Zones Information
  log " * Querying the Zone Information Endpoint..."
  log " * ${luadns_api_url}/zones"
  log " * Json Response is shown below:"
  curl_api_call "${luadns_api_url}/zones" | jq || true
  log ""
  sleep $wait_time

  # 3. Zone Information for what's in the Config File
  log " * Querying the Zone Information: ${dns_zone_name} Endpoint..."
  log " * ${luadns_api_url}/zones/${zone_id}"
  log " * Json Response is shown below:"
  curl_api_call "${luadns_api_url}/zones/${zone_id}" | jq || true
  log ""
}

######################################
# Verify the Updates
######################################

# Verify Updated Records
verify_dns_records() {
  local record dns_wait_time
  local N_nameservers=${#luadns_nameservers[@]}
  local N_records=${#dns_record_names[@]}
  local delay_time=2
  local retries=10
  local i=0
  local j=0
  local k=0
  log_to_email "Verifying Updated DNS Record(s)..."

  # Loop Through Each of the Records
  for ((i=0; i<=(N_records-1); i++)); do
    log_to_email " * Querying LuaDNS Nameservers for ${dns_record_names[$i]}..."

    # Loop Through Each of the Nameservers
    for ((j=0; j<=(N_nameservers-1); j++));do

      # Try Querying each Nameserver up to a max of $retries
      for ((k=1; k<=retries; k++)); do
        dns_wait_time=$((delay_time**k))
        sleep $dns_wait_time
    
        # Check to see if the record has been deployed or not
        if query_nameserver "${luadns_nameservers[$j]}" "${dns_record_names[$i]}" "${public_ip}"; then
          log_to_email "    - Record live on ${luadns_nameservers[$j]}"
          break
        elif (( k == retries )); then
          log_to_both "    - Record not live after retrying $retries times - Exiting"
          notify_and_record_warning
          exit 1 
        fi
      done 
    done
  done

  # Correct Records were returned in above cases
  log_to_both " * Success! All Updated Record(s) now Live!"
}

# Notify of Success
notify_and_record_success() {

  # Only Notify on an IP Change, or if the last update failed
  if [[ "${ip_change}" == "yes" || "${last_update_failed}" == "yes" ]]; then

    # Send Email & Call Notification Hook
    send_email "DDNS Update OK: ${dns_record_names[0]}" "${logfile}"

    # Call Notification Hook if defined
    if [[ -x "${notification_hook}" ]]; then
      log " * Calling Notification Hook: ${notification_hook}"
      if "${notification_hook}" "DDNS Update OK: ${dns_record_names[0]}" "${hook_logfile}"; then
        log " * Success"
      else
        log " * Notification Hook returned error code?"
      fi
    fi
    log ""
  fi

  # Record new Public IP and Status
  log "${public_ip}" > "${last_ip_check_file}"
  log "ok" > "${last_update_status_file}"
}

# Notify of Success
notify_and_record_warning() {

  # Send Email & Call Notification Hook
  send_email "DDNS Update Error(s): ${dns_record_names[0]}" "${logfile}"

  # Call Notification Hook if defined
  if [[ -x "${notification_hook}" ]]; then
    log " * Calling Notification Hook: ${notification_hook}"
    if "${notification_hook}" "DDNS Update Error(s): ${dns_record_names[0]}" "${hook_logfile}"; then
      log " * Success"
    else
      log " * Notification Hook returned error code?"
    fi
  fi
  log ""

  # Record the Result as "error"
  log "error" > "${last_update_status_file}"

  # Clean Up Logfiles
  clean_up_logfiles
}

# Send Email with Mutt if Emails are Enabled
send_email() {
  local email_subject="${1}"
  local email_body="${2}"

  # Check Emails are not disabled
  if [[ "${disable_emails}" == "no" ]]; then

    # If Hostname & OS Name were determined, add them here
    if [[ -n "${system_hostname}" && -n "${os_name}" ]]; then
      log_to_email ""
      log_to_email "Regards," &> /dev/null
      log_to_email "${system_hostname}" &> /dev/null
    fi

    # Define mutt input arguments 
    mutt_args=(-F "${muttrc_path}" -s "$email_subject" "${email_address}")

    # Call mutt to send the email - Check success for the logs
    log "Emailing ${email_address}..."
    if mutt "${mutt_args[@]}" < "${email_body}"; then
      log " * Notification Email sent successfully..."
    else
      log " * Problem sending Notification Email..."
    fi
  fi
}

# Clean up tempory logfiles
clean_up_logfiles() {
  log "Removing /tmp files..."
  rm -f "${logfile}" "${hook_logfile}"
  log ""
}

######################################
# Call Main Function
######################################
main "$@"

