#!/bin/sh

set -e

# Delete drop-in file if present
delete_dropin_file() {
  if [ -f "$dropin_file" ]
  then
    rm "$dropin_file"
  fi
}

# Remove working directory to prevent warnings from dpkg
delete_working_dir() {
  if [ -d "$working_dir" ]
  then
    rm -rf "$working_dir"
  fi
}

# Package Name, Drop-In File
package_name="luadns-ddns"
dropin_dir="/etc/systemd/system/${package_name}.service.d"
dropin_file="${dropin_dir}/user.conf"
working_dir="/var/lib/luadns-ddns"

# Determine action
action="${1}"

# Check if the service/timer are active and stop them, the postrm then
# will disable them accordingly.
# No DEBHELPER Snippet added below as dh_installsystemd
# is called in debian/rules with --no-enable and --no-start
# ...so need to add this here.
if [ "${action}" = "remove" ]
then
  if [ -z "$DPKG_ROOT" ] && [ -d /run/systemd/system ]
  then
    deb-systemd-invoke stop "$package_name"".service" \
                            "$package_name"".timer" >/dev/null || true 
  fi

  # Delete the working directory and dropin file
  delete_working_dir
  delete_dropin_file
fi

#DEBHELPER#

exit 0


